spring.application.name=CloudManage
server.port=${SERVER_PORT:8080}

# Configuración de logging para mejor visibilidad en la consola
spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:h2:mem:cloudmanagedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=false

management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

info.app.name=Microservicio de CloudNative
info.app.version=@project.version@
info.app.description=API REST para sistema de Cursos

cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
cloud.aws.credentials.session-token=${AWS_SESSION_TOKEN}
cloud.aws.region.static=us-east-1
cloud.s3.bucket-name=s3-cloudmanage
cloud.efs.mount-path=/mnt/efs
cloud.s3.region=us-east-1

# Configuración de OAuth2 Resource Server para Azure AD B2C
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_B2C_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AZURE_B2C_JWK_URI}


# Timeout de conexión para JWKS
spring.security.oauth2.resourceserver.jwt.jwk-set-cache-lifetime=300s
spring.security.oauth2.resourceserver.jwt.jwk-set-cache-refresh-interval=150s

# Configuracion de RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123
spring.rabbitmq.listener.simple.default-requeue-rejected=false
